language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8

script:
  - coverage run --omit=*.virtualenvs*,*virtualenv* src/manage.py test --settings=sous-chef.settings_test member meal order notification delivery note billing
  - pep8 --count --show-source --exclude=migrations src/
  # Run `makemessages` and report an error if it should have been run by the
  # developer for this pull request.
  - python3 src/manage.py makemessages -l fr
  # We allow for a 1-line difference since `makemessages` will change the
  # timestamp within the file.
  - git diff --numstat | awk '{if ($1>1 || $2>1) { print "***ERROR***\nLarge diff detected in", $3; print "Please run `python3 src/manage.py makemessages -l fr` and commit."; exit 1 } else { exit 0 }}'

after_success:
  - coveralls
